### ISSUE TITLE
ModuleNotFoundError: No module named 'model_utils'

### ISSUE THREAD

**Issue by MengzhangLI** [victorychain/Adversarial-Policy-Gradient-for-Deep-Learning-Image-Augmentation#1]
Hi Kaiyang, thanks for your share.

When I implemented it on my server, I met the error below:

> Traceback (most recent call last):
>   File "apga_mura.py", line 1670, in <module>
>     if __name__ == '__main__': fire.Fire(mura_experiment)
>   File "/home/mcmong/anaconda3/envs/APGA/lib/python3.6/site-packages/fire/core.py", line 138, in Fire
>     component_trace = _Fire(component, args, parsed_flag_args, context, name)
>   File "/home/mcmong/anaconda3/envs/APGA/lib/python3.6/site-packages/fire/core.py", line 471, in _Fire
>     target=component.__name__)
>   File "/home/mcmong/anaconda3/envs/APGA/lib/python3.6/site-packages/fire/core.py", line 675, in _CallAndUpdateTrace
>     component = fn(*varargs, **kwargs)
>   File "apga_mura.py", line 44, in mura_experiment
>     from model_utils import random_eraser
> ModuleNotFoundError: No module named 'model_utils'

Seems like there may be a .py file named `model_utils.py` isn't it?

Best,

**Comment by MengzhangLI** [comment]
Well, I've fixed it by using `random_eraser.py` from here:
 
[https://github.com/yu4u/cutout-random-erasing/blob/master/random_eraser.py](url)

However, there are some other bugs as shown below:

<img width="1430" alt="snapshot" src="https://user-images.githubusercontent.com/24582831/71541892-769e2700-299a-11ea-8a70-b1963901b749.png">

Seems like these bugs are caused by refactoring from command line(like Jupyter Notebook) to .py file, can you refactor this project? Thank you very much.

Best,

**Comment by shivamakhauri04** [comment]
Same issue. Can you upload the original .ipynb file or the supporting files. I can then look into refactoring or fixing small errors if any
